Implement ExecuteOnKey map method
hazelcast/hazelcast-go-client pull request #626
Opened 2021-09-09 11:00 UTC by JorgenPo

Resolves #624

2021-09-09 11:00 UTC, devOpsHazelcast commented
[![CLA assistant check](https://cla.hazelcast.org/pull/badge/not_signed)](https://cla.hazelcast.org/hazelcast/hazelcast-go-client?pullRequest=626) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.hazelcast.org/hazelcast/hazelcast-go-client?pullRequest=626) before we can accept your contribution.<br/><hr/>**George Popoff** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.hazelcast.org/check/hazelcast/hazelcast-go-client?pullRequest=626) it.</sub>

2021-09-09 12:43 UTC, yuce commented
Hi @JorgenPo Thanks for your PR! Could you also add a test to the PR?

2021-09-09 12:48 UTC, yuce requested changes

2021-09-09 12:48 UTC, yuce commented on proxy_map.go
> +
This blank line is not necessary.

2021-09-09 12:48 UTC, yuce commented on proxy_map.go
> +
This blank line is not necessary.

2021-09-10 09:06 UTC, JorgenPo commented
> Hi @JorgenPo Thanks for your PR! Could you also add a test?

Sure, I'll try to add a test for the function

2021-09-10 10:27 UTC, yuce commented
Thanks! I've added a test for `ExecuteOnEntries`. The same setup can also be used for `ExecuteOnKey`.

2021-09-10 10:28 UTC, yuce commented
Would it be possible for you to merge https://github.com/hazelcast/hazelcast-go-client/pull/630/files into your PR, so you can immediately access that setup?

2021-09-13 08:36 UTC, JorgenPo commented
> Would it be possible for you to merge https://github.com/hazelcast/hazelcast-go-client/pull/630/files into your PR, so you can immediately access that setup?

I merged your commit and added a test for ExecuteOnKey

2021-09-15 14:29 UTC, JorgenPo commented on proxy_map.go
> +
Fixed this

2021-09-20 07:34 UTC, yuce commented
Thanks @JorgenPo, we'll merge this after releasing v1.1.1

2021-11-10 07:46 UTC, yuce commented
Hi @JorgenPo I'm about to merge this PR, but could you sign the CLA and resolve the conflict in `map_it_test.go`?

2021-12-10 08:26 UTC, utku-caglayan commented
@JorgenPo sadly we need to continue this wok on another PR since we need to provide it on v1.2.0. Sorry for the inconvenience. Your contributions are always welcome!

2021-12-10 08:26 UTC, closed without merging