Add TLS/SSL code samples and documentation.
hazelcast/hazelcast-go-client pull request #920
Opened 2023-01-25 15:27 UTC by mehmettokgoz

- Two sample showing how to configure Go client with SSL enabled and Mutual Authentication enabled are added. 
- A new section to documentation is added to show the TLS/SSL options.

2023-02-01 13:48 UTC, yuce requested changes
Looks good, here are a few ideas...

2023-02-02 08:14 UTC, mehmettokgoz commented on doc.go
> +Setting this option to False will result in discarding the other SSL options.
Updated: https://github.com/hazelcast/hazelcast-go-client/pull/920/commits/352f2b627ac5f310f70d2be6f45c5e19456cab0e

2023-02-02 08:14 UTC, mehmettokgoz commented on doc.go
> +You can either edit the hazelcast.Config object or create a cluster.SSLConfig{} instance and then assign it to config.Cluster.Network.SSL.
Removed at https://github.com/hazelcast/hazelcast-go-client/pull/920/commits/352f2b627ac5f310f70d2be6f45c5e19456cab0e.

2023-02-02 08:14 UTC, mehmettokgoz commented on doc.go
> +To use it, see the TLS/SSL for Hazelcast Members section: https://docs.hazelcast.com/hazelcast/latest/security/tls-ssl.html#tlsssl-for-hazelcast-members
Removed this section at https://github.com/hazelcast/hazelcast-go-client/pull/920/commits/352f2b627ac5f310f70d2be6f45c5e19456cab0e.

2023-02-02 08:14 UTC, mehmettokgoz commented on doc.go
> +One of the offers of Hazelcast is the TLS/SSL protocol which you can use to establish an encrypted communication across your cluster with key stores and trust stores.
Updated at https://github.com/hazelcast/hazelcast-go-client/pull/920/commits/352f2b627ac5f310f70d2be6f45c5e19456cab0e.

2023-02-02 08:14 UTC, mehmettokgoz commented on examples/ssl/simple/main.go
> +	fmt.Println("Connection Successful!")
Switched these two lines at https://github.com/hazelcast/hazelcast-go-client/pull/920/commits/352f2b627ac5f310f70d2be6f45c5e19456cab0e.

2023-02-02 08:15 UTC, mehmettokgoz commented on examples/ssl/simple/main.go
> +	config := hazelcast.NewConfig()
Updated at https://github.com/hazelcast/hazelcast-go-client/pull/920/commits/352f2b627ac5f310f70d2be6f45c5e19456cab0e.

2023-03-01 09:14 UTC, yuce approved these changes
Looks good!

2023-03-01 09:57 UTC, merged